export const paymentForms = [
  { value: "01", label: "01: Efectivo" },
  { value: "02", label: "02: Cheque nominativo" },
  { value: "03", label: "03: Transferencia electrónica de fondos" },
  { value: "04", label: "04: Tarjeta de crédito" },
  { value: "05", label: "05: Monedero electrónico" },
  { value: "06", label: "06: Dinero electrónico" },
  { value: "08", label: "08: Vales de despensa" },
  { value: "12", label: "12: Dación en pago" },
  { value: "13", label: "13: Pago por subrogación" },
  { value: "14", label: "14: Pago por consignación" },
  { value: "15", label: "15: Condonación" },
  { value: "17", label: "17: Compensación" },
  { value: "23", label: "23: Novación" },
  { value: "24", label: "24: Confusión" },
  { value: "25", label: "25: Remisión de deuda" },
  { value: "26", label: "26: Prescripción o caducidad" },
  { value: "27", label: "27: A satisfacción del acreedor" },
  { value: "28", label: "28: Tarjeta de débito" },
  { value: "29", label: "29: Tarjeta de servicios" },
  { value: "30", label: "30: Aplicación de anticipos" },
  { value: "31", label: "31: Intermediario pagos" },
  { value: "99", label: "99: Por definir" },
];
