export const PERMISOS = {
  VISTAS: {
    ADMIN: "view.admin",
    INICIO: "view.inicio",
    PROVEEDOR_PAGOS: "view.proveedor-pagos",
    PROVEEDOR_PAGOS_PAGADOS: "view.proveedor-pagados",
    RESERVAS: "view.reservas",
    CLIENTES: "view.clientes",
    HOTELES: "view.hoteles",
    SOLICITUDES: "view.solicitudes",
    PAGOS: "view.pagos",
    FACTURAS: "view.facturas",
    FACTURAS_PREPAGO: "view.fact-prepago",
    FACTURAS_CREDITO: "view.fact-cred",
    CONFIRMATION_CODE: "view.confirm-code",
    VIAJEROS: "view.viajeros",
    APLICACION_DE_SALDO: "view.apli-sald",
    CUENTAS_POR_COBRAR: "view.cuenta-cobr",
    PROVEEDORES: "view.proveedores",
    MIA_TARJETAS: "view.mia.tarjetas",
    MIA_TITULARES: "view.mia.titulares",
  },
  COMPONENTES: {
    BOTON: {
      PAGAR_PROVEEDOR: "button.pagar-proveedor-reserva",
      CREAR_RESERVA: "button.crear-reserva",
      EDITAR_PRECIO_RESERVA: "button.edit-price-booking",
      ACTUALIZAR_PDF_FACTURA: "button.actualizar_factura_pdf",
      MIA_TARJETAS_CREAR: "button.mia.tarjetas.crear",
      MIA_TARJETAS_EDITAR: "button.mia.tarjetas.editar",
      MIA_TARJETAS_ELIMINAR: "button.mia.tarjetas.eliminar",
      CANCELAR_RESERVA: "button.cancelar.bookings",
      MIA_TITULARES_CREAR: "button.mia.titulares.crear",
      MIA_TITULARES_EDITAR: "button.mia.titulares.editar",
      MIA_TITULARES_ELIMINAR: "button.mia.titulares.eliminar",
    },
    GROUP: {
      PROVEEDORES_EDICIONES: "button.proveedores.edicion",
      PROVEEDORES_EDICIONES_FINANZAS: "button.proveedores.fiscal",
    },
  },
  VERSION: {
    AGREGAR_WALLET_OPERACIONES: "modal.operaciones-agregar-wallet",
    AGREGAR_WALLET_FINANZAS: "modal.finanzas-agregar-wallet",
    PROVEEDORES_FINANZAS: "view.finanzas.proveedores",
  },
} as const;
